name: heba_project
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  rubber:
  flutter_images_slider:
  solid_bottom_sheet:
  firebase_analytics:
  rounded_floating_app_bar:
  image_picker:
  ansicolor:
  cached_network_image: ^2.0.0-rc
  intl:
  firebase_storage:
  google_maps_flutter: ^0.5.27
  geoflutterfire:
  location:
  flutter_image_compress:
  uuid:
  image_cropper:
  animator:
  cloud_firestore:
  multi_image_picker:
  firebase_auth: ^0.15.4
  popup_menu:
  google_sign_in:
  provider:
  flutter_spinkit:
  rflutter_alert:
  flutter_reaction_button:
  ff_navigation_bar:
  google_fonts_arabic:
  toast:
  material_segmented_control:
  dashed_container:
  logger:
  http:
  json_serializable:
  flutter_svg:
  adobe_xd:

  get_it:  # add this line
  rxdart:  # add this line
  flutter_emoji:
  custom_radio_grouped_button:
  scoped_model:
  flutter_form_builder:
  grouped_buttons:
  timeago:
  outline_material_icons:
  carousel_slider:
  font_awesome_flutter:
  connectivity:
  sticky_headers:
  sqflite:
  path_provider:
  google_maps_place_picker:
  url_launcher:
  modal_progress_hud:
  geolocator:
  tuple:
  shared_preferences:
  fluttertoast:
  flutter_staggered_grid_view:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
flash:
firebase_database:
dev_dependencies:
  pedantic: ^1.4.0
  build_runner: ^1.2.7
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #    - assets/student.json
    - assets/images/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/ca.ttf
        - style: italic
        - asset: assets/fonts/Cairo-Black.ttf
        - style: italic
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - style: italic
        - asset: assets/fonts/Cairo-Light.ttf
        - style: italic
        - asset: assets/fonts/Cairo-Regular.ttf

